"""user update password to password_hash

Revision ID: 081dd54a97ad
Revises: 5e4fe2f3a46a
Create Date: 2025-07-08 12:18:27.792154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081dd54a97ad'
down_revision = '5e4fe2f3a46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
