"""adding occupation to patients

Revision ID: 572d75874425
Revises: defaa9e8d78d
Create Date: 2025-07-17 12:39:15.709533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572d75874425'
down_revision = 'defaa9e8d78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocupation', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('ocupation')

    # ### end Alembic commands ###
