"""adding rut to patients

Revision ID: 84485a1f5dcf
Revises: 
Create Date: 2025-07-17 10:24:44.861452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84485a1f5dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut_prefix', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rut_suffix', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('rut_suffix')
        batch_op.drop_column('rut_prefix')

    # ### end Alembic commands ###
