"""adding notes to sessions

Revision ID: b10fcfcd0bea
Revises: 572d75874425
Create Date: 2025-07-17 14:17:12.008019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10fcfcd0bea'
down_revision = '572d75874425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_patients')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('notes')

    op.create_table('_alembic_tmp_patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone_number_1', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone_number_2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address_1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('address_2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('join_date', sa.DATETIME(), nullable=False),
    sa.Column('medical_history', sa.VARCHAR(length=200), nullable=True),
    sa.Column('current_medications', sa.VARCHAR(length=200), nullable=True),
    sa.Column('allergies', sa.VARCHAR(length=200), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rut_prefix', sa.INTEGER(), nullable=True),
    sa.Column('rut_suffix', sa.VARCHAR(length=1), nullable=True),
    sa.Column('deceased', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
