"""adding deceasxed flag

Revision ID: defaa9e8d78d
Revises: 84485a1f5dcf
Create Date: 2025-07-17 11:44:48.326227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defaa9e8d78d'
down_revision = '84485a1f5dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deceased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('deceased')

    # ### end Alembic commands ###
