import os

# SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
# SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_DATABASE_URI = 'sqlite:///jennyapp.db'
SECRET_KEY = 'supersecretkey'
SQLALCHEMY_TRACK_MODIFICATIONS = False